CREATE TABLE [dbo].[Pitching](
	[playerID] [nvarchar](9) NOT NULL,
	[yearID] [smallint] NOT NULL,
	[stint] [smallint] NOT NULL,
	[teamID] [nvarchar](3) NULL,
	[lgID] [nvarchar](2) NULL,
	[W] [smallint] NULL,
	[L] [smallint] NULL,
	[G] [smallint] NULL,
	[GS] [smallint] NULL,
	[CG] [smallint] NULL,
	[SHO] [smallint] NULL,
	[SV] [smallint] NULL,
	[IPouts] [int] NULL,
	[H] [smallint] NULL,
	[ER] [smallint] NULL,
	[HR] [smallint] NULL,
	[BB] [smallint] NULL,
	[SO] [smallint] NULL,
	[BAOpp] [float] NULL,
	[ERA] [float] NULL,
	[IBB] [smallint] NULL,
	[WP] [smallint] NULL,
	[HBP] [smallint] NULL,
	[BK] [smallint] NULL,
	[BFP] [smallint] NULL,
	[GF] [smallint] NULL,
	[R] [smallint] NULL,
	[SH] [smallint] NULL,
	[SF] [smallint] NULL,
	[GIDP] [smallint] NULL
)
WITH(CLUSTERED COLUMNSTORE INDEX);
GO

CREATE TABLE [dbo].[People](
	[playerID] [nvarchar](255) NULL,
	[birthYear] [int] NULL,
	[birthMonth] [int] NULL,
	[birthDay] [int] NULL,
	[birthCountry] [nvarchar](255) NULL,
	[birthState] [nvarchar](255) NULL,
	[birthCity] [nvarchar](255) NULL,
	[deathYear] [int] NULL,
	[deathMonth] [int] NULL,
	[deathDay] [int] NULL,
	[deathCountry] [nvarchar](255) NULL,
	[deathState] [nvarchar](255) NULL,
	[deathCity] [nvarchar](255) NULL,
	[nameFirst] [nvarchar](255) NULL,
	[nameLast] [nvarchar](255) NULL,
	[nameGiven] [nvarchar](255) NULL,
	[weight] [int] NULL,
	[height] [int] NULL,
	[bats] [nvarchar](255) NULL,
	[throws] [nvarchar](255) NULL,
	[debut] [nvarchar](255) NULL,
	[finalGame] [nvarchar](255) NULL,
	[retroID] [nvarchar](255) NULL,
	[bbrefID] [nvarchar](255) NULL
) WITH(CLUSTERED INDEX(playerID));
GO

CREATE TABLE [dbo].[Teams](
	[yearID] [smallint] NOT NULL,
	[lgID] [nvarchar](2) NOT NULL,
	[teamID] [nvarchar](3) NOT NULL,
	[franchID] [nvarchar](3) NULL,
	[divID] [nvarchar](1) NULL,
	[Rank] [smallint] NULL,
	[G] [smallint] NULL,
	[Ghome] [smallint] NULL,
	[W] [smallint] NULL,
	[L] [smallint] NULL,
	[DivWin] [nvarchar](1) NULL,
	[WCWin] [nvarchar](1) NULL,
	[LgWin] [nvarchar](1) NULL,
	[WSWin] [nvarchar](1) NULL,
	[R] [smallint] NULL,
	[AB] [smallint] NULL,
	[H] [smallint] NULL,
	[2B] [smallint] NULL,
	[3B] [smallint] NULL,
	[HR] [smallint] NULL,
	[BB] [smallint] NULL,
	[SO] [smallint] NULL,
	[SB] [smallint] NULL,
	[CS] [smallint] NULL,
	[HBP] [smallint] NULL,
	[SF] [smallint] NULL,
	[RA] [smallint] NULL,
	[ER] [smallint] NULL,
	[ERA] [float] NULL,
	[CG] [smallint] NULL,
	[SHO] [smallint] NULL,
	[SV] [smallint] NULL,
	[IPouts] [int] NULL,
	[HA] [smallint] NULL,
	[HRA] [smallint] NULL,
	[BBA] [smallint] NULL,
	[SOA] [smallint] NULL,
	[E] [int] NULL,
	[DP] [int] NULL,
	[FP] [float] NULL,
	[name] [nvarchar](50) NULL,
	[park] [nvarchar](255) NULL,
	[attendance] [int] NULL,
	[BPF] [int] NULL,
	[PPF] [int] NULL,
	[teamIDBR] [nvarchar](3) NULL,
	[teamIDlahman45] [nvarchar](3) NULL,
	[teamIDretro] [nvarchar](3) NULL
) WITH(CLUSTERED INDEX(yearID, teamID));
GO

CREATE TABLE [dbo].[TeamsFranchises](
	[franchID] [nvarchar](3) NOT NULL,
	[franchName] [nvarchar](50) NULL,
	[active] [nvarchar](2) NULL,
	[NAassoc] [nvarchar](3) NULL
) WITH(HEAP, DISTRIBUTION = REPLICATE);
GO

CREATE TABLE [dbo].[Batting](
	[playerID] [nvarchar](9) NOT NULL,
	[yearID] [smallint] NOT NULL,
	[stint] [smallint] NOT NULL,
	[teamID] [nvarchar](3) NULL,
	[lgID] [nvarchar](2) NULL,
	[G] [smallint] NULL,
	[G_batting] [smallint] NULL,
	[AB] [smallint] NULL,
	[R] [smallint] NULL,
	[H] [smallint] NULL,
	[2B] [smallint] NULL,
	[3B] [smallint] NULL,
	[HR] [smallint] NULL,
	[RBI] [smallint] NULL,
	[SB] [smallint] NULL,
	[CS] [smallint] NULL,
	[BB] [smallint] NULL,
	[SO] [smallint] NULL,
	[IBB] [smallint] NULL,
	[HBP] [smallint] NULL,
	[SH] [smallint] NULL,
	[SF] [smallint] NULL,
	[GIDP] [smallint] NULL
) WITH(CLUSTERED COLUMNSTORE INDEX);
GO
